In [3]:
import pandas as pd
import numpy as np

In [4]:
ubsWorksheet = pd.read_csv("/content/Unidades_Basicas_Saude-UBS.csv", sep=';', decimal=',', on_bad_lines='skip')

ubsWorksheet

,CNES,UF,IBGE,NOME,LOGRADOURO,BAIRRO,LATITUDE,LONGITUDE
0,33820,52,520170,UNIDADE DE SAUDE DA FAMILIA PSF 307,RUA H,NOVO MUNDO,-15.90682,-52.22545
1,108,26,260290,USF ALTO DOS INDIOS,RUA 17,PONTE DOS CARVALHOS,-8.28389,-35.03210
2,116,26,260290,USF CHARNECA II,RUA 02,CHARNECA,-8.28353,-35.02819
3,124,26,260290,USF SAO FRANCISCO I,RUA MANOEL DOMINGOS BARROS,SAO FRANCISCO,-8.28700,-35.03500
4,132,26,260290,USF ROSARIO,RUA 01,ROSARIO,-8.28389,-35.03210
...,...,...,...,...,...,...,...,...
40362,2288656,33,330420,USF BAIXADA DA OLARIA,RUA HENRI ANTOINE GROUES ABBE PIERRE,BAIXADA DA OLARIA,-22.47278,-44.48366
40363,5680557,15,150220,UNIDADE DE SAUDE DA FAMILIA DR MANOEL VALENTE,RUA BOM JARDIM,D JOAO VI,-1.19599,-47.18128
40364,6320600,31,314315,UNIDADE BASICA DE SAUDE VIRGULINA RAMALHO DOS ...,RUA ALVARO MOURA,CENTRO,-16.86600,-41.25500
40365,7831765,29,291840,USF CURACA NH3,PROJETO CURACA NH3,CURACA NH3,-9.41400,-40.50300
40366,7959184,35,355040,UBS BELA SAO PEDRO SAO PEDRO,RUA OLIVIA NEUMMAN GOMES,JDM BELA SAO PEDRO,-22.54900,-47.91400

In [5]:
UbsEstado = {
    
    'SP':len(ubsWorksheet.query('UF == 35')),
    'MG':len(ubsWorksheet.query('UF == 31')),
    'BA':len(ubsWorksheet.query('UF == 29')),
    'RJ':len(ubsWorksheet.query('UF == 33')),
    'ES':len(ubsWorksheet.query('UF == 32')),
    'SE':len(ubsWorksheet.query('UF == 28')),
    'AL':len(ubsWorksheet.query('UF == 27')),
    'PE':len(ubsWorksheet.query('UF == 26')),
    'PB':len(ubsWorksheet.query('UF == 25')),
    'RN':len(ubsWorksheet.query('UF == 24')),
    'CE':len(ubsWorksheet.query('UF == 23')),
    'PI':len(ubsWorksheet.query('UF == 22')),
    'MA':len(ubsWorksheet.query('UF == 21')),
    'TO':len(ubsWorksheet.query('UF == 17')),
    'AP':len(ubsWorksheet.query('UF == 16')),
    'PA':len(ubsWorksheet.query('UF == 15')),
    'RR':len(ubsWorksheet.query('UF == 14')),
    'AM':len(ubsWorksheet.query('UF == 13')),
    'AC':len(ubsWorksheet.query('UF == 12')),
    'RO':len(ubsWorksheet.query('UF == 11')),
    'PR':len(ubsWorksheet.query('UF == 41')),
    'SC':len(ubsWorksheet.query('UF == 42')),
    'RS':len(ubsWorksheet.query('UF == 43')),
    'MS':len(ubsWorksheet.query('UF == 50')),
    'MT':len(ubsWorksheet.query('UF == 51')),
    'GO':len(ubsWorksheet.query('UF == 52')),
    'DF':len(ubsWorksheet.query('UF == 53'))
    
}

In [9]:
estado = ['SP','MG','BA','RJ','ES','SE','AL','PE','PB','RN','CE','PI','MA','TO','AP','PA','RR','AM','AC','RO','PR','SC','RS','MS','MT','GO','DF']

ubsEstado = [len(ubsWorksheet.query('UF == 35')), len(ubsWorksheet.query('UF == 31')), len(ubsWorksheet.query('UF == 29')), len(ubsWorksheet.query('UF == 33')), len(ubsWorksheet.query('UF == 32')), len(ubsWorksheet.query('UF == 28')), len(ubsWorksheet.query('UF == 27')), len(ubsWorksheet.query('UF == 26')), len(ubsWorksheet.query('UF == 25')), len(ubsWorksheet.query('UF == 24')), len(ubsWorksheet.query('UF == 23')), len(ubsWorksheet.query('UF == 22')), len(ubsWorksheet.query('UF == 21')), len(ubsWorksheet.query('UF == 17')), len(ubsWorksheet.query('UF == 16')), len(ubsWorksheet.query('UF == 15')), len(ubsWorksheet.query('UF == 14')), len(ubsWorksheet.query('UF == 13')), len(ubsWorksheet.query('UF == 12')), len(ubsWorksheet.query('UF == 11')), len(ubsWorksheet.query('UF == 41')), len(ubsWorksheet.query('UF == 42')), len(ubsWorksheet.query('UF == 43')), len(ubsWorksheet.query('UF == 50')), len(ubsWorksheet.query('UF == 51')), len(ubsWorksheet.query('UF == 52')), len(ubsWorksheet.query('UF == 53'))]

#2021 - IBGE(Wikipedia)
popEstado = ['46.649.132', '21.411.923', '14.985.284', '17.463.349', '4.108.508', '2.338.474', '3.365.351', '9.674.793', '4.059.905', '3.560.903', '9.240.580', '3.289.290', '7.153.262', '1.607.363', '877.613', '8.777.124', '652.713', '4.269.995', '906.876', '1.815.278', '11.597.484', '7.338.473', '11.466.630', '2.839.188', '3.567.234', '7.206.589', '3.094.325']

#2019 - IBGE(Site IBGE)
pibEstado = ['2.348.338.000.000', '651.873.000.000', '293.241.000.000', '779.928.000.000', '137.346.000.000', '44.689.000.000', '58.964.000.000', '197.853.000.000', '67.986.000.000', '71.337.000.000', '163.575.000.000', '52.781.000.000', '97.340.000.000', '39.356.000.000', '17.497.000.000', '178.377.000.000', '14.292.000.000', '108.181.000.000', '15.630.000.000', '47.091.000.000', '466.377.000.000', '323.264.000.000', '482.464.000.000', '106.943.000.000', '142.122.000.000', '208.672.000.000', '273.614.000.000']

In [10]:
for i in range(27):
  print('Estado:', estado[i])
  print('População:', popEstado[i])
  print('PIB:', pibEstado[i])
  print('Número de UBS: ', ubsEstado[i])
  print()

Estado: SP
População: 46.649.132
PIB: 2.348.338.000.000
Número de UBS:  5026

Estado: MG
População: 21.411.923
PIB: 651.873.000.000
Número de UBS:  5248

Estado: BA
População: 14.985.284
PIB: 293.241.000.000
Número de UBS:  3863

Estado: RJ
População: 17.463.349
PIB: 779.928.000.000
Número de UBS:  1811

Estado: ES
População: 4.108.508
PIB: 137.346.000.000
Número de UBS:  806

Estado: SE
População: 2.338.474
PIB: 44.689.000.000
Número de UBS:  490

Estado: AL
População: 3.365.351
PIB: 58.964.000.000
Número de UBS:  880

Estado: PE
População: 9.674.793
PIB: 197.853.000.000
Número de UBS:  2498

Estado: PB
População: 4.059.905
PIB: 67.986.000.000
Número de UBS:  1474

Estado: RN
População: 3.560.903
PIB: 71.337.000.000
Número de UBS:  985

Estado: CE
População: 9.240.580
PIB: 163.575.000.000
Número de UBS:  2144

Estado: PI
População: 3.289.290
PIB: 52.781.000.000
Número de UBS:  1099

Estado: MA
População: 7.153.262
PIB: 97.340.000.000
Número de UBS:  2015

Estado: TO
População: 1.607.363
PIB: 39.356.000.000
Número de UBS:  429

Estado: AP
População: 877.613
PIB: 17.497.000.000
Número de UBS:  139

Estado: PA
População: 8.777.124
PIB: 178.377.000.000
Número de UBS:  1582

Estado: RR
População: 652.713
PIB: 14.292.000.000
Número de UBS:  130

Estado: AM
População: 4.269.995
PIB: 108.181.000.000
Número de UBS:  572

Estado: AC
População: 906.876
PIB: 15.630.000.000
Número de UBS:  226

Estado: RO
População: 1.815.278
PIB: 47.091.000.000
Número de UBS:  281

Estado: PR
População: 11.597.484
PIB: 466.377.000.000
Número de UBS:  2007

Estado: SC
População: 7.338.473
PIB: 323.264.000.000
Número de UBS:  1675

Estado: RS
População: 11.466.630
PIB: 482.464.000.000
Número de UBS:  1987

Estado: MS
População: 2.839.188
PIB: 106.943.000.000
Número de UBS:  605

Estado: MT
População: 3.567.234
PIB: 142.122.000.000
Número de UBS:  906

Estado: GO
População: 7.206.589
PIB: 208.672.000.000
Número de UBS:  1313

Estado: DF
População: 3.094.325
PIB: 273.614.000.000
Número de UBS:  176